---
name: Hello CI

on:
  push:
    branches:
      - main
      - "week2-**"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  workflow_dispatch:

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello CI"
